### ISSUE TITLE
SECRET_KEY  error problem

### ISSUE THREAD

**Issue by bluebamus** [delitamakanda/dopejob#1]
when I try to run the project.
it show me the error code like below.

`  File "/root/git_source/dopejob-master-venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/git_source/dopejob-master/project/settings.py", line 24, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "/root/git_source/dopejob-master-venv/lib/python3.5/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/root/git_source/dopejob-master-venv/lib/python3.5/site-packages/decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "/root/git_source/dopejob-master-venv/lib/python3.5/site-packages/decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
`

**Comment by delitamakanda** [comment]
Seems you don't have environments variables installed with the python-decouple package.

for doing that stuff:

set virtual environement with virtualenv with python3 support:

`shell
virtualenv venv -p python3
`

for mac users
`shell
source venv/bin/activate 
`

for windows users
`shell
.\venv\Scripts\activate
`

install packages for django
`shell
pip install -r requirements-dev.txt
`

create a config file *.env* in your root folder,  same level that manage.py with the content below
----
SECRET_KEY=dummy_secret_key
DEBUG=True
OTHER_VARIABLE=variable_1
---

to generate a secret key [this is a free website for doing this](https://www.miniwebtool.com/django-secret-key-generator/).

Hope this help !

**Comment by bluebamus** [comment]
`7857:~/git_source/dopejob-master# python manage.py runserver 0:8000
Performing system checks...

System check identified no issues (0 silenced).
August 26, 2018 - 18:14:54
Django version 2.0.2, using settings 'project.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f8354ce0bf8>
Traceback (most recent call last):
  File "/root/git_source/venv/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/root/git_source/venv/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/root/git_source/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/git_source/dopejob-master/project/wsgi.py", line 13, in <module>
    from whitenoise.django import DjangoWhiteNoise
  File "/root/git_source/venv/lib/python3.5/site-packages/whitenoise/django.py", line 2, in <module>
    '\n\n'
ImportError:

Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
This can be fixed by following the upgrade instructions at:
http://whitenoise.evans.io/en/stable/changelog.html#v4-0



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/git_source/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/root/git_source/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 141, in inner_run
    handler = self.get_handler(*args, **options)
  File "/root/git_source/venv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/root/git_source/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 66, in get_handler
    return get_internal_wsgi_application()
  File "/root/git_source/venv/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'project.wsgi.application' could not be loaded; Error importing module.
`

ok now I find new error msg.

is it reqiured wsgi setting by nginx or apache?
if you leave a msg, I'll try, and share on here

**Comment by bluebamus** [comment]
and, leave tips here.

I made the file of 'config.env' at root forder, same level with manage.py.
but it doesn't work.
So, I change codes in project/setting.py like below

SECRET_KEY = '0ff1vl2nj4-#stv^#b0=18dy%)5+kat6j7fz)h$e0$#m8cyh4u'
DEBUG = True
ALLOWED_HOSTS = '*'

thank you.

**Comment by delitamakanda** [comment]
Hello,

it is not config.env just ".env" should work. it's important to hide sensible informations like secret keys, 3rd party authentication.

for wsgi settings i choose nginx

**Comment by delitamakanda** [comment]
whitenoise==4.0 is incompatible. Downgrade to 3.2 instead

**Comment by bluebamus** [comment]
dude.... it's very hard to downgrade whitenoise from 4.0 to 3.2
before setting wsgi in nginx on my system,
I just wanted to run it using runserver.

hmm....

**Comment by kkyadav11** [comment]
File "C:\Users\kkyad\Envs\venv\lib\site-packages\decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: ADMIN_EMAIL not found. Declare it as envvar or define a default value.
