### ISSUE TITLE
Secret Key Problem

### ISSUE THREAD

**Issue by frchnrzm** [delitamakanda/dopejob#4]
i try to run the project, but it show the error code like below

Traceback (most recent call last):
  File "D:\ele\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\ele\env\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "D:\ele\env\lib\site-packages\django\core\management\__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "D:\ele\env\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "D:\ele\env\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\ele\env\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\gujang\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\ele\myelearning\settings.py", line 27, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "D:\ele\env\lib\site-packages\decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "D:\ele\env\lib\site-packages\decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "D:\ele\env\lib\site-packages\decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

**Comment by delitamakanda** [comment]
At the root of the project, same level than "manage.py" create an .env file with :

`SECRET_KEY=<put_random_key_here`

**Comment by frchnrzm** [comment]
already create and .env file with secret key, but the errors are still the same

(myproject) D:\dopejob-master>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\dopejob-master\myproject\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\dopejob-master\myproject\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "D:\dopejob-master\myproject\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "D:\dopejob-master\myproject\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\dopejob-master\myproject\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\gujang\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\dopejob-master\project\settings.py", line 24, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "D:\dopejob-master\myproject\lib\site-packages\decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "D:\dopejob-master\myproject\lib\site-packages\decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "D:\dopejob-master\myproject\lib\site-packages\decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

**Comment by delitamakanda** [comment]
if virtualenv set python3 binary, you could check
`python3 manage.py makemigrations` or `python3 manage.py runserver`

**Comment by frchnrzm** [comment]
the virtualenvironment doesn't use python3

still have error on secret key.

please check the pic
did i put the .env file correctly ?
![Capture](https://user-images.githubusercontent.com/50861182/63358262-f553d980-c394-11e9-8781-7704cbc2eabc.JPG)

**Comment by delitamakanda** [comment]
Sorry for late answer :) i think `ConfigFile.env` is the problem. 
Try rename this file without filename just leave the extension` .env`  with notepad or vscode
